#!/bin/bash

#Submit this script with: sbatch thefilename
#SBATCH --time=24:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=16G   # memory per CPU
#SBATCH --mail-user=bret_hess@byu.edu   # email address
#sBATCH --mail-type=FAIL
#SBATCH --mail-type=END
#SBATCH --job-name=graphenertm_row1



python /fslhome/bch/graphener/graphener_bch/graphener/Main.py > out

